modality: "text-image"
num_classes: 6
batch_size: 32
learning_rate: 1.0e-4
num_epochs: 2
dropout_p: 0.1
text_embedder: "all-mpnet-base-v2"
trained_model_version: "version_87"
trained_model_path: null
gpus: [0]
train_data_path: "./data/multimodal_train.tsv"
val_data_path: "./data/multimodal_validate.tsv"
test_data_path: "./data/multimodal_test_public.tsv"
preprocessed_train_dataframe_path: "./data/train__text_image_dataframe.pkl"
preprocessed_val_dataframe_path: "./data/val__text_image_dataframe.pkl"
preprocessed_test_dataframe_path: "./data/test__text_image_dataframe.pkl"
